---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/customers/auth":
    post:
      summary: Sign up as a customer
      tags:
      - Customers
      parameters: []
      responses:
        '200':
          description: Customer created
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
                username:
                  type: string
              required:
              - email
              - password
              - password_confirmation
  "/api/v1/customers/auth/sign_in":
    post:
      summary: Sign in customer
      tags:
      - Customers
      parameters: []
      responses:
        '200':
          description: Customer signed in
          headers:
            authorization:
              schema:
                type: string
              description: Bearer authentication header
        '401':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
              - password_confirmation
  "/api/v1/customers/auth/sign_out":
    delete:
      summary: Sign out customer
      tags:
      - Customers
      parameters: []
      responses:
        '200':
          description: Customer signed in
        '401':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
              - password_confirmation
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
